### ISSUE TITLE
Explore articles by categories

### ISSUE THREAD

**Issue by kwreen** [justin-cotarla/big-wiki-crew#23]
Story for Epic #22 

As a user, I would like to use categories to explore articles in Wikipedia.

* [x] #25 : Setup category service to query for/by categories
* [x] #26 : Implement category page layout
* [x] #27 : Add category card to homepage
* [x] #43 : Integrate category service into category page and card
* [x] #44 : Implement category article results page
* [x]  UI design for all tasks
* [x]  UI / Unit tests for all tasks

[Story Points: 8]
[Priority: High]
[Risk: Medium]

![paper soen 390 mockups 5 1](https://user-images.githubusercontent.com/16171727/53848310-d2b63b80-3f81-11e9-8254-7f69cf6ff163.png)

| Test | Input | Expected Output | Status |
| --- | --- | --- | --- |
| 1. Categories Feed Card | Click on the Categories feed card in the main feed. | Categories page launches and shows the top categories.| PASS |
 | 2. Explore on Category | Click on any top category card (e.g. Culture) | Display of a list of articles belonging to the selected category. | PASS |
 | 3. Opening Article | Click on article result in list. | Page article is launched. | PASS |
