### ISSUE TITLE
Search categories

### ISSUE THREAD

**Issue by kwreen** [justin-cotarla/big-wiki-crew#24]
Story for Epic #22 

As a user, I would like to search for categories in Wikipedia.

* [x]  #28 : Implement category search service
* [x]  #29 : Integrate category search into category activity
* [x]  #64 : Implement display for category searching
* [x]  #65 : Add category recommendation
* [x] UI design for all tasks
* [x]  UI / Unit tests for all tasks

[Story Points: 8]
[Priority: High]
[Risk: Medium]

![paper soen 390 mockups 6](https://user-images.githubusercontent.com/23409994/52448902-628fd380-2b03-11e9-80e7-0adbb695defc.png)

| Test | Input | Expected Output | Status |
| --- | --- | --- | --- |
| 1. Categories Feed Card | Click on the Categories feed card in the main feed. | Categories page launches and shows the top categories.| PASS |
 | 2. Search for Category | Enter category search term in the search bar at the top of the screen. | Display list of category results matching the searched term. | PASS |
 | 3. Explore on Category | Click on a single category search result from list. | Display list of articles belonging to the selected category. | PASS |
 | 4. Opening Article | Click on article result in list. | Page article is launched. | PASS |
