### ISSUE TITLE
Note Taking

### ISSUE THREAD

**Issue by kwreen** [justin-cotarla/big-wiki-crew#69]
As a user, I want to be able to take notes in Wikipedia. I want to be able to highlight sections in an article to note down in the application. I want to be able to refer to my notes while on the article, and also to be able to refer back to all my notes in a dedicated section of Wikipedia. I want my notes to be organized by their respective articles.

- [x] Design note taking UX
- [x] Design note taking UI
- [x] #71 : Implement note taking layout [2 pts]
- [x] #72 : Implement notes page layout [3 pts]
- [x] #73 : Implement note data structure [1 pt]
- [x] #74 : Implement note taking service [5 pts] (2 assignees)
- [x] #75 : Add note-to-article link [2 pts]
- [x] #76 : Add article-to-note link [4 pts]
- [x] #115 : Implement note view layout [2 pts]
- [x] #125 : Implement notes list sorting [2 pts]
- [x] Add all relevant UI tests
- [x] Add all relevant unit tests

[Story Points: 21]
[Priority: High]
[Risk: High]

![image](https://user-images.githubusercontent.com/16171727/56182849-04d7a600-5fe2-11e9-82ac-2c11a1e62ead.png)

| Test | Input | Expected Output | Status |
| --- | --- | --- | --- |
| 1. Article Page | Highlight text by selection | `Save Note` menu option appears | PASS |
| 2. Text Selection Menu Option | Click on `Save Note` option | "Note saved" confirmation dialog pops up from the bottom. | PASS |
| 3. Article Menu Tab | Click on notes icon at the 6th position | Notes viewer dialog opens up from the bottom with the respective notes for the current article. | PASS |
| 4.  Notes Viewer Dialog | Long press on a note | A context menu opens up for the respective note. | PASS |
| 5. Note Context Menu | Click on `Copy` option | Note is copied to user's clipboard. | PASS |
| 6. Note Context Menu | Click on `Delete` option | Note is deleted and disappears from the view. | PASS |
| 7. Saved Tab | Click on `Saved` tab from main application menu | Page for saved lists opens up. | PASS |
| 8. Saved Notes Tab | Click on `Notes` tab from the Saved page | Page view switches to list of notes. | PASS |
| 9. Notes Menu | Click on three-dot menu for Notes | Option to sort notes appear. | PASS |
| 10. `Sort by` Option | Click on a sorting option | List of notes are sorted in the selected option. | PASS |
| 11. Note Item | Click on an item in the notes list view | Page view of the respective note opens up. | PASS |
| 12. View Article | Click on `View Article` from the note view | User is lead to the article page from which the note was taken. | PASS |
