### ISSUE TITLE
Chat Room

### ISSUE THREAD

**Issue by kwreen** [justin-cotarla/big-wiki-crew#70]
As a user, I want to be able to chat with other readers currently viewing the same article. I want to be able to discuss with others about the current article as an anonymous user.

- [x] Design chat room UX
- [x] Design chat room UI
- [x] #78 : Implement chat room button [4 pts]
- [x] #79 : Implement chat room box layout [5 pts] (2 assignees)
- [x] #80 : Implement chat service [5 pts] (2 assignees)
- [x] #81 : Implement user connections [3 pts]
- [x] #82 : Set up onboarding for chat [4 pts]
- [x] Add all relevant UI tests
- [x] Add all relevant unit tests

[Story Points: 21]
[Priority: High]
[Risk: High]

![image](https://user-images.githubusercontent.com/16171727/56182776-b1fdee80-5fe1-11e9-806f-0d8cf4a43694.png)

| Test | Input | Expected Output | Status |
| --- | --- | --- | --- |
| 1. Article Page | Chat room button in sight | See updated count of users viewing the same article. | PASS |
 | 2. Chat Room Button | Click on button at the bottom right of the page | Chat room dialog opens. | PASS |
 | 3. Incoming Messages | View chat room box | Incoming messages from users have anonymous profile ids and icons. | PASS |
 | 4.  Input Box | Click on chat room input box | Keyboard appears to allow users to type in any input. | PASS |
 | 5. Send Button | Click on send button | Outgoing message from input box is dispatched. Message can be seen in the chat room box by users in the room. | PASS |
